INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Taroudannt');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Agadir');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Rabat');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Fès');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Casablanca');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Marrakech');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Tanger');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Oujda');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Salé');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Kénitra');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Safi');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Mohammedia');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Settat');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Khouribga');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Essaouir');

