--delete from POSTAVAIABLECITIES;


INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Taroudann');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Agadi');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Raba');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Fè');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Casablanc');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Marrakec');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Tange');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Oujd');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Sal�');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Kénitr');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Saf');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Mohammedi');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Setta');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Khouribg');

INSERT INTO POSTAVAIABLECITIES (NAMES) VALUES ('Essaoui');


commit
