--delete from POSTDELIVERY_LINE where id!=1;

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('3', 'Taroudannt', 'Agadir');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('4', 'Taroudannt', 'Rabat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('5', 'Taroudannt', 'Fès');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('6', 'Taroudannt', 'Casablanca');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('7', 'Taroudannt', 'Marrakech');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('8', 'Taroudannt', 'Tanger');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('9', 'Taroudannt', 'Oujda');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('10', 'Taroudannt', 'Salé');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('11', 'Taroudannt', 'Kénitra');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('12', 'Taroudannt', 'Safi');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('13', 'Taroudannt', 'Mohammedia');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('14', 'Taroudannt', 'Settat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('15', 'Taroudannt', 'Khouribga');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('16', 'Taroudannt', 'Essaouira');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('17', 'Agadir', 'Taroudannt');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('19', 'Agadir', 'Rabat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('20', 'Agadir', 'Fès');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('21', 'Agadir', 'Casablanca');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('22', 'Agadir', 'Marrakech');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('23', 'Agadir', 'Tanger');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('24', 'Agadir', 'Oujda');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('25', 'Agadir', 'Salé');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('26', 'Agadir', 'Kénitra');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('27', 'Agadir', 'Safi');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('28', 'Agadir', 'Mohammedia');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('29', 'Agadir', 'Settat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('30', 'Agadir', 'Khouribga');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('31', 'Agadir', 'Essaouira');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('32', 'Rabat', 'Taroudannt');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('33', 'Rabat', 'Agadir');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('35', 'Rabat', 'Fès');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('36', 'Rabat', 'Casablanca');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('37', 'Rabat', 'Marrakech');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('38', 'Rabat', 'Tanger');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('39', 'Rabat', 'Oujda');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('40', 'Rabat', 'Salé');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('41', 'Rabat', 'Kénitra');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('42', 'Rabat', 'Safi');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('43', 'Rabat', 'Mohammedia');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('44', 'Rabat', 'Settat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('45', 'Rabat', 'Khouribga');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('46', 'Rabat', 'Essaouira');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('47', 'Fès', 'Taroudannt');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('48', 'Fès', 'Agadir');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('49', 'Fès', 'Rabat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('51', 'Fès', 'Casablanca');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('52', 'Fès', 'Marrakech');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('53', 'Fès', 'Tanger');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('54', 'Fès', 'Oujda');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('55', 'Fès', 'Salé');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('56', 'Fès', 'Kénitra');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('57', 'Fès', 'Safi');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('58', 'Fès', 'Mohammedia');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('59', 'Fès', 'Settat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('60', 'Fès', 'Khouribga');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('61', 'Fès', 'Essaouira');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('62', 'Casablanca', 'Taroudannt');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('63', 'Casablanca', 'Agadir');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('64', 'Casablanca', 'Rabat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('65', 'Casablanca', 'Fès');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('67', 'Casablanca', 'Marrakech');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('68', 'Casablanca', 'Tanger');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('69', 'Casablanca', 'Oujda');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('70', 'Casablanca', 'Salé');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('71', 'Casablanca', 'Kénitra');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('72', 'Casablanca', 'Safi');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('73', 'Casablanca', 'Mohammedia');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('74', 'Casablanca', 'Settat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('75', 'Casablanca', 'Khouribga');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('76', 'Casablanca', 'Essaouira');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('77', 'Marrakech', 'Taroudannt');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('78', 'Marrakech', 'Agadir');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('79', 'Marrakech', 'Rabat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('80', 'Marrakech', 'Fès');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('81', 'Marrakech', 'Casablanca');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('83', 'Marrakech', 'Tanger');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('84', 'Marrakech', 'Oujda');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('85', 'Marrakech', 'Salé');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('86', 'Marrakech', 'Kénitra');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('87', 'Marrakech', 'Safi');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('88', 'Marrakech', 'Mohammedia');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('89', 'Marrakech', 'Settat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('90', 'Marrakech', 'Khouribga');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('91', 'Marrakech', 'Essaouira');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('92', 'Tanger', 'Taroudannt');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('93', 'Tanger', 'Agadir');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('94', 'Tanger', 'Rabat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('95', 'Tanger', 'Fès');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('96', 'Tanger', 'Casablanca');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('97', 'Tanger', 'Marrakech');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('99', 'Tanger', 'Oujda');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('100', 'Tanger', 'Salé');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('101', 'Tanger', 'Kénitra');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('102', 'Tanger', 'Safi');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('103', 'Tanger', 'Mohammedia');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('104', 'Tanger', 'Settat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('105', 'Tanger', 'Khouribga');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('106', 'Tanger', 'Essaouira');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('107', 'Oujda', 'Taroudannt');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('108', 'Oujda', 'Agadir');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('109', 'Oujda', 'Rabat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('110', 'Oujda', 'Fès');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('111', 'Oujda', 'Casablanca');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('112', 'Oujda', 'Marrakech');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('113', 'Oujda', 'Tanger');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('115', 'Oujda', 'Salé');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('116', 'Oujda', 'Kénitra');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('117', 'Oujda', 'Safi');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('118', 'Oujda', 'Mohammedia');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('119', 'Oujda', 'Settat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('120', 'Oujda', 'Khouribga');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('121', 'Oujda', 'Essaouira');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('122', 'Salé', 'Taroudannt');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('123', 'Salé', 'Agadir');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('124', 'Salé', 'Rabat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('125', 'Salé', 'Fès');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('126', 'Salé', 'Casablanca');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('127', 'Salé', 'Marrakech');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('128', 'Salé', 'Tanger');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('129', 'Salé', 'Oujda');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('131', 'Salé', 'Kénitra');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('132', 'Salé', 'Safi');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('133', 'Salé', 'Mohammedia');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('134', 'Salé', 'Settat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('135', 'Salé', 'Khouribga');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('136', 'Salé', 'Essaouira');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('137', 'Kénitra', 'Taroudannt');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('138', 'Kénitra', 'Agadir');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('139', 'Kénitra', 'Rabat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('140', 'Kénitra', 'Fès');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('141', 'Kénitra', 'Casablanca');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('142', 'Kénitra', 'Marrakech');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('143', 'Kénitra', 'Tanger');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('144', 'Kénitra', 'Oujda');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('145', 'Kénitra', 'Salé');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('147', 'Kénitra', 'Safi');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('148', 'Kénitra', 'Mohammedia');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('149', 'Kénitra', 'Settat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('150', 'Kénitra', 'Khouribga');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('151', 'Kénitra', 'Essaouira');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('152', 'Safi', 'Taroudannt');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('153', 'Safi', 'Agadir');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('154', 'Safi', 'Rabat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('155', 'Safi', 'Fès');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('156', 'Safi', 'Casablanca');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('157', 'Safi', 'Marrakech');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('158', 'Safi', 'Tanger');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('159', 'Safi', 'Oujda');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('160', 'Safi', 'Salé');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('161', 'Safi', 'Kénitra');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('163', 'Safi', 'Mohammedia');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('164', 'Safi', 'Settat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('165', 'Safi', 'Khouribga');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('166', 'Safi', 'Essaouira');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('167', 'Mohammedia', 'Taroudannt');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('168', 'Mohammedia', 'Agadir');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('169', 'Mohammedia', 'Rabat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('170', 'Mohammedia', 'Fès');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('171', 'Mohammedia', 'Casablanca');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('172', 'Mohammedia', 'Marrakech');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('173', 'Mohammedia', 'Tanger');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('174', 'Mohammedia', 'Oujda');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('175', 'Mohammedia', 'Salé');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('176', 'Mohammedia', 'Kénitra');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('177', 'Mohammedia', 'Safi');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('179', 'Mohammedia', 'Settat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('180', 'Mohammedia', 'Khouribga');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('181', 'Mohammedia', 'Essaouira');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('182', 'Settat', 'Taroudannt');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('183', 'Settat', 'Agadir');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('184', 'Settat', 'Rabat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('185', 'Settat', 'Fès');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('186', 'Settat', 'Casablanca');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('187', 'Settat', 'Marrakech');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('188', 'Settat', 'Tanger');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('189', 'Settat', 'Oujda');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('190', 'Settat', 'Salé');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('191', 'Settat', 'Kénitra');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('192', 'Settat', 'Safi');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('193', 'Settat', 'Mohammedia');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('195', 'Settat', 'Khouribga');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('196', 'Settat', 'Essaouira');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('197', 'Khouribga', 'Taroudannt');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('198', 'Khouribga', 'Agadir');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('199', 'Khouribga', 'Rabat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('200', 'Khouribga', 'Fès');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('201', 'Khouribga', 'Casablanca');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('202', 'Khouribga', 'Marrakech');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('203', 'Khouribga', 'Tanger');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('204', 'Khouribga', 'Oujda');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('205', 'Khouribga', 'Salé');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('206', 'Khouribga', 'Kénitra');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('207', 'Khouribga', 'Safi');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('208', 'Khouribga', 'Mohammedia');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('209', 'Khouribga', 'Settat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('211', 'Khouribga', 'Essaouira');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('212', 'Essaouira', 'Taroudannt');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('213', 'Essaouira', 'Agadir');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('214', 'Essaouira', 'Rabat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('215', 'Essaouira', 'Fès');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('216', 'Essaouira', 'Casablanca');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('217', 'Essaouira', 'Marrakech');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('218', 'Essaouira', 'Tanger');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('219', 'Essaouira', 'Oujda');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('220', 'Essaouira', 'Salé');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('221', 'Essaouira', 'Kénitra');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('222', 'Essaouira', 'Safi');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('223', 'Essaouira', 'Mohammedia');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('224', 'Essaouira', 'Settat');

INSERT INTO POSTDELIVERY_LINE (ID, FROM_, TO_) VALUES ('225', 'Essaouira', 'Khouribga');

